name: wallet
description: Crypto wallet package for Bitcoin, Ethereum and Tron written in pure Dart.
version: 0.0.3
repository: https://github.com/xclud/dart_wallet
homepage: https://github.com/xclud/dart_wallet

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bech32: ^0.2.1
  bip39: ^1.0.6
  collection: ^1.15.0
  crypto: ^3.0.1
  decimal: ^2.1.0
  hex: ^0.2.0
  pointycastle: ^3.5.1
  tron: ^0.0.1
  web3dart: ^2.3.4

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.0
