name: wallet
description: Crypto wallet package for Dart and Flutter.
version: 0.0.1
repository: https://github.com/xclud/dart_wallet
homepage: https://github.com/xclud/dart_wallet

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

dev_dependencies:
  lints: ^1.0.0
  test: ^1.17.10